:doctype: article
:author: Jerod Gawne
:email: jerod.gawne@53.com
:docdate: June 05, 2020
:revdate: {docdatetime}
:description: Password Safe How to Request Credentials
:keywords: password-safe, rest, api
:sectanchors:
:sectlinks:
:sectnums:
:toc:
:experimental:
:icons: font
:checkedbox: pass:normal[{startsb}&#10004;{endsb}]
:checkbox: pass:normal[{startsb}  {endsb}]
:source-highlighter: rouge
:listing-caption: Listing

= Password Safe: How to Request Credentials

Author: {author} | Last Update: {revdate}


NOTE: Utilizes Password Safe API Documentation v6.10

== SignIn
Page 18 of the documentation.

POST /Auth/SignAppin
[source, http, linenums]
POST https://stgpasswordsafe.info53.com/BeyondTrust/api/public/v3/Auth/SignAppin

This requires an HTTP header to be sent that includes your credentials.
[source, http, linenums]
Authorization: PS-Auth key=<api_key>; runas=<api_user>;

Response
[source, json, linenums]
{
  "UserId": 56,
  "SID": null,
  "EmailAddress": "soumya.kalakonda@53.com",
  "UserName": "apiCCAS",
  "Name": "apiCCAS"
}

Return includes a cookie that you will need to capture and attach to all future requests.

e.g.
[source, bash, linenums]
ASP.NET_SessionId=gguqqawjkixe3e5vcmngpnpu; Path=/; Secure; HttpOnly; SameSite=None; Domain=sogramihqpama90.info53.com

The specific portion of the cookie required is: ASP.NET_SessionId=<session_id>


== Find Account
Page 178-180 of the documentation.

NOTE: This step is optional if you already know the accountId you would like a password for.

This endpoint requires the url parameters 'systemName' and 'accountName'

GET /ManagedAccounts?systemName=<system_name>&AccountName=<account_name>

[source, http, linenums]
GET https://stgpasswordsafe.info53.com/BeyondTrust/api/public/v3/ManagedAccounts?systemName=SQL-Oracle&AccountName=FCXTIIS1.SUGRAMIHQSQLF45

Response
[source, json, linenums]
{
  "PlatformID": 75,
  "SystemId": 55,
  "SystemName": "SQL-Oracle",
  "InstanceName": "",
  "DomainName": null,
  "AccountId": 36672,
  "AccountName": "FCXTIIS1.SUGRAMIHQSQLF45",
  "ApplicationID": null,
  "ApplicationDisplayName": null,
  "MaximumReleaseDuration": 120,
  "DefaultReleaseDuration": 120,
  "LastChangeDate": "2019-10-31T17:41:15.253",
  "NextChangeDate": null,
  "IsChanging": false,
  "IsISAAccess": false,
  "PreferredNodeID": "3da71763-c0ca-4853-aebf-7a879c7062ac"
}


== Make a Request
Page 268-270 of the documentation.

This requires SystemId and AccountId from the previous step.

POST /Requests with JSON body

JSON Body
[source, json, linenums]
{
	"SystemID": 55,
	"AccountID": 36672,
	"Reason": "testing",
	"DurationMinutes": 120
}

Response (RequestID)
[source, text, linenums]
4594


== Retrieve Credentials
Page 132-133 of the documentation

GET /Credentials/<request_id>

[source, http, linenums]
GET https://stgpasswordsafe.info53.com/BeyondTrust/api/public/v3/Credentials/4594

Response
[source, json, linenums]
"spEs76duswAkacHuRi2e"


== Checkin Request
Page 272 of the documentation

This is performed when the credentials are no longer needed.

PUT /Requests/<id>/Checkin with JSON Body

[source, http, linenums]
PUT https://stgpasswordsafe.info53.com/BeyondTrust/api/public/v3/Requests/4594/Checkin


JSON Body
[source, json, linenums]
{
	"Reason": "Done testing."
}

Response
[source, json, linenums]
HTTP 204 'No Content'


== SignOut
Page 19 of the documentation.

POST /Auth/Signout

[source, http, linenums]
https://stgpasswordsafe.info53.com/BeyondTrust/api/public/v3/Auth/SignOut

Response
[source, json, linenums]
HTTP 200 'OK'
